"""increase password length for bcrypt

Revision ID: 091de3f544af
Revises: e0ad156379c0
Create Date: 2026-06-21 23:59:22.936349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091de3f544af'
down_revision = 'e0ad156379c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('user',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
